spring:
  application:
    name: USER-SERVICE
  datasource:
    hikari:
      username: root
      password: 12345
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/microservice-test?createDatabaseIfNotExist=true

  config:
    import: "optional:configserver:http://localhost:8080"

